#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("/lib/helpers.star", "get_bom_data_for_tkr_name", "get_image_repo_for_component", "ValuesFormatStr")
#@ load("tanzu-addons-manager_addon_data.lib.yaml", "tanzuaddonsmanagerdatavalues")

#@ def tanzuaddonsmanagerpackageyaml():

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-addons-package-sa
  namespace: tkg-system
  annotations:
    tkg.tanzu.vmware.com/addon-type: "packages/management-package"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-addons-package-cluster-role
  annotations:
    tkg.tanzu.vmware.com/addon-type: "packages/management-package"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-addons-package-cluster-rolebinding
  annotations:
    tkg.tanzu.vmware.com/addon-type: "packages/management-package"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-addons-package-cluster-role
subjects:
- kind: ServiceAccount
  name: tanzu-addons-package-sa
  namespace: tkg-system
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-addons-manager
  namespace: tkg-system
  annotations:
    tkg.tanzu.vmware.com/addon-type: "packages/management-package"
spec:
  serviceAccountName: tanzu-addons-package-sa
  packageRef:
    refName: addons-manager.tanzu.vmware.com
    #! In alpha9 release, kapp-controller's implementation shows this field is optional,
    #! however InstalledPackage CR has error status if not provide versionSelection.
    #! It complains about "Unsupported version selection type (currently supported: semver)" from this CR.
    #! To workaround, we add versionSelection and use the tag from TKR Bom as version constraints, and this is also aligned
    #! with what package CLI plugin does.
    versionSelection:
      prereleases: {}
  values:
  - secretRef:
      name: tanzu-addons-manager-data-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-addons-manager-data-values
  namespace: tkg-system
  annotations:
    tkg.tanzu.vmware.com/addon-type: "packages/management-package"
type: Opaque
stringData:
  values.yaml: #@ ValuesFormatStr.format(yaml.encode(tanzuaddonsmanagerdatavalues()))

#@ end
